# Generated by Django 5.0.7 on 2024-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('image', models.URLField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
